# 事件
on:
  push

# 工作
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: macos-latest
      - run: ./gradlew -v
