# 事件
on:
  push

permissions:
  contents: write

# 工作
jobs:
  ci:
    name: build and test java project
    runs-on: ubuntu-latest
    steps:
      - name: fetch branch content
        uses: actions/checkout@v4

      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: check java version
        run: java -version

      - name: check gradle version
        run: gradle -version

      - name: build with gradle
        run: gradle build

      - name: check current directory
        run: ls -la

      - name: build with Spring Boot
        run: gradle bootJar

      # & 符號，在後台運行
      - name: run Spring Boot app
        run: gradle bootRun &

      - name: wait for app start
        run: |
          echo "waiting for spring boot to start"
          sleep 30

      #$(): 命令替換。它允許將命令的輸出用作另一個命令的參數。
      #-ne: 數值比較運算符。它表示“不等於”，用於比較兩個數字。
      #[]: 測試命令。用於評估條件表達式。

      - name: Test app endpoints
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080/hello)
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Application did not start successfully"
            exit 1
          fi
        shell: bash

      #lsof: 代表 "list open files"（列出打開的文件）。這是一個用於列出被進程打開的文件信息的命令。
      #-t: 這個選項告訴 lsof 生成簡潔的輸出，只包括使用指定文件的進程 ID（PID）。
      #-i: 這個選項用於選擇列出與指定的 Internet 地址匹配的文件。在這個例子中，-i:8080 指定與端口 8080 相關的文件。

      - name: stop app
        run: kill $(lsof -t -i:8080)
        shell: bash

  push-docker-hub:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: fetch branch content
        uses: actions/checkout@v4

      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: check java version
        run: java -version

      - name: check gradle version
        run: gradle -version

      - name: build with gradle
        run: gradle build

      - name: check current directory
        run: ls -la

      - name: check jar Exists
        run:  ls build/libs | grep '\.jar$'

      - name: connect docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push docker repository
        uses: docker/build-push-action@v6
        with:
          push: 'true'
          tags: yihao0826/practice-devops:latest

  cd:
    name: deploy java project
    needs: push-docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: fetch branch content
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no cindle@${{ secrets.SSH_REMOTE_SERVER }} 'bash -s' << 'EOF'
            sudo docker pull yihao0826/practice-devops:latest
            sudo docker run -d -p 8080:8080 yihao0826/practice-devops:latest
          EOF
