# 事件
on:
  push

# 工作
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
  job2:
    runs-on: windlws-latest
    steps:
      - run: echo "hello ~"
      - run: java -version
