# 事件
on:
  push

# 工作
jobs:
  ci:
    name: build java project
    runs-on: ubuntu-latest
    steps:
      - name: fetch branch content
        uses: actions/checkout@v4

      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: check java version
        run: java -version

      - name: build with gradle
        run: ./gradlew build

      - name: build with Spring Boot
        run: ./gradle bootJar

      - name: run Spring Boot app
        run: ./gradle bootRun


